import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT_ROOT = path.join(ROOT, 'content');

const TYPES = [
  { value: 'video', folder: 'video' },
  { value: 'mindmap', folder: 'mindmap' },
  { value: 'flashcards', folder: 'flashcards' },
  { value: 'lab', folder: 'labs' },
  { value: 'html_embed', folder: 'html_embed' },
  { value: 'game', folder: 'game' },
  { value: 'summary', folder: 'summary' },
];

function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60) || `item-${Date.now()}`;
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

async function ask(rl, question, fallback = '') {
  const suffix = fallback ? ` [${fallback}]` : '';
  const answer = (await rl.question(`${question}${suffix}: `)).trim();
  return answer || fallback;
}

async function askRequired(rl, question) {
  while (true) {
    const answer = (await rl.question(`${question}: `)).trim();
    if (answer) return answer;
    console.log('  This field is required.');
  }
}

function writeJson(filePath, data) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

function placeholderThumb(destDir) {
  const assets = path.join(destDir, 'assets');
  fs.mkdirSync(assets, { recursive: true });
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#7C3AED"/><stop offset="1" stop-color="#F59E0B"/></linearGradient></defs>
  <rect width="640" height="360" fill="url(#g)"/>
  <circle cx="320" cy="180" r="48" fill="white" fill-opacity="0.92"/>
  <polygon points="310,155 310,205 352,180" fill="#7C3AED"/>
</svg>`;
  const thumbPath = path.join(assets, 'thumb.svg');
  fs.writeFileSync(thumbPath, svg, 'utf8');
  return 'assets/thumb.svg';
}

function placeholderHtml(destDir, title, filename) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    body { font-family: 'Plus Jakarta Sans', system-ui, sans-serif; margin: 0; min-height: 100vh; display: grid; place-items: center; background: #F5F3FF; color: #111827; }
    .card { background: white; border-radius: 24px; padding: 32px; max-width: 420px; box-shadow: 0 10px 30px rgba(124,58,237,.12); text-align: center; }
    h1 { color: #7C3AED; margin: 0 0 8px; }
  </style>
</head>
<body>
  <div class="card">
    <h1>${title}</h1>
    <p>Placeholder page generated by <code>npm run add-content</code>.</p>
  </div>
</body>
</html>
`;
  fs.writeFileSync(path.join(destDir, filename), html, 'utf8');
}

async function collectData(rl, type, destDir, title) {
  if (type === 'video') {
    const url = await askRequired(rl, 'Video URL (YouTube / Vimeo / Drive)');
    const provider = await ask(rl, 'Provider (youtube|vimeo|drive)', 'youtube');
    const durationMinutes = Number(await ask(rl, 'Duration in minutes', '10')) || 10;
    return { url, provider, durationMinutes };
  }

  if (type === 'mindmap') {
    const format = await ask(rl, 'Format (image|markdown)', 'markdown');
    if (format === 'image') {
      const imagePath = await ask(rl, 'Image path relative to this folder', 'assets/mindmap.png');
      return { format: 'image', imagePath };
    }
    const outline = await ask(rl, 'Markdown outline (use \\n for new lines)', '- Root\\n  - Branch 1\\n  - Branch 2');
    return { format: 'markdown', outline: outline.replace(/\\n/g, '\n') };
  }

  if (type === 'flashcards') {
    const cards = [];
    console.log('Enter flashcards. Leave the front blank to finish.');
    while (true) {
      const front = (await rl.question(`  Card ${cards.length + 1} front: `)).trim();
      if (!front) break;
      const back = await askRequired(rl, '  Card back');
      cards.push({ front, back });
    }
    if (cards.length === 0) {
      throw new Error('At least one flashcard is required.');
    }
    return { cards };
  }

  if (type === 'lab') {
    const instructions = await askRequired(rl, 'Instructions (markdown)');
    const stepsRaw = await ask(rl, 'Steps (comma-separated)', '');
    const steps = stepsRaw ? stepsRaw.split(',').map((s) => s.trim()).filter(Boolean) : [];
    const resourceLinks = [];
    const linkLabel = (await rl.question('Resource label (blank to skip): ')).trim();
    if (linkLabel) {
      const url = await askRequired(rl, 'Resource URL');
      resourceLinks.push({ label: linkLabel, url });
    }
    return { instructions, steps, resourceLinks };
  }

  if (type === 'html_embed') {
    const source = (await rl.question('Path to an HTML file to copy (blank = placeholder): ')).trim();
    if (source && fs.existsSync(source)) {
      fs.copyFileSync(source, path.join(destDir, 'page.html'));
    } else {
      placeholderHtml(destDir, title, 'page.html');
    }
    return { file: 'page.html' };
  }

  if (type === 'game') {
    const source = (await rl.question('Path to an HTML file to copy (blank = placeholder): ')).trim();
    if (source && fs.existsSync(source)) {
      fs.copyFileSync(source, path.join(destDir, 'index.html'));
    } else {
      placeholderHtml(destDir, title, 'index.html');
    }
    const thumbnail = placeholderThumb(destDir);
    return { file: 'index.html', thumbnail };
  }

  if (type === 'summary') {
    const body = await askRequired(rl, 'Summary body (markdown)');
    return { body };
  }

  return {};
}

async function main() {
  const rl = readline.createInterface({ input, output });
  try {
    console.log('\nFutureMinds content scaffolder\n');
    console.log(TYPES.map((t, i) => `  ${i + 1}. ${t.value}`).join('\n'));
    const choice = await askRequired(rl, 'Choose a type number or name');
    const selected =
      TYPES.find((t) => t.value === choice) ||
      TYPES[Number(choice) - 1];
    if (!selected) throw new Error('Unknown content type.');

    const title = await askRequired(rl, 'Title');
    const description = await ask(rl, 'Description', '');
    const tagsRaw = await ask(rl, 'Tags (comma-separated)', '');
    const tags = tagsRaw.split(',').map((t) => t.trim()).filter(Boolean);
    const slug = slugify(await ask(rl, 'Slug', slugify(title)));

    const destDir = path.join(CONTENT_ROOT, selected.folder, slug);
    if (fs.existsSync(destDir)) {
      throw new Error(`Folder already exists: ${destDir}`);
    }
    fs.mkdirSync(destDir, { recursive: true });

    const data = await collectData(rl, selected.value, destDir, title);
    if (!data || typeof data !== 'object') {
      throw new Error('Type-specific data is required.');
    }

    const manifest = {
      id: slug,
      type: selected.value,
      title,
      description,
      tags,
      dateAdded: today(),
      data,
    };

    const manifestPath = path.join(destDir, 'manifest.json');
    writeJson(manifestPath, manifest);
    console.log(`\nCreated ${path.relative(ROOT, destDir)}`);
    console.log(`Manifest: ${path.relative(ROOT, manifestPath)}`);
    console.log('Restart or refresh the Vite dev server if the new item is not listed yet.\n');
  } catch (error) {
    console.error(`\n${error.message}\n`);
    process.exitCode = 1;
  } finally {
    rl.close();
  }
}

main();
